/* Generated by reswrap version 3.1.0 */

/* created by reswrap from file continue.gif */
extern const unsigned char continue_gif[];

/* created by reswrap from file icon16.gif */
extern const unsigned char icon16_gif[];

/* created by reswrap from file icon32.gif */
extern const unsigned char icon32_gif[];

/* created by reswrap from file pause.gif */
extern const unsigned char pause_gif[];

/* created by reswrap from file pc00.gif */
extern const unsigned char pc00_gif[];

/* created by reswrap from file pc01.gif */
extern const unsigned char pc01_gif[];

/* created by reswrap from file pc02.gif */
extern const unsigned char pc02_gif[];

/* created by reswrap from file pc03.gif */
extern const unsigned char pc03_gif[];

/* created by reswrap from file pc04s.gif */
extern const unsigned char pc04s_gif[];

/* created by reswrap from file play.gif */
extern const unsigned char play_gif[];

/* created by reswrap from file stop.gif */
extern const unsigned char stop_gif[];

/* created by reswrap from file swap.gif */
extern const unsigned char swap_gif[];

/* created by reswrap from file time.gif */
extern const unsigned char time_gif[];

